[package]
name = "astrum-os"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.2.7"
bitbybit = "1.3.2"
limine = "0.2.0"
noto-sans-mono-bitmap = { version = "0.3.0", features = ["size_24", "unicode_ranges_all"] }
